version: '2.3'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: peertube
      POSTGRES_PASSWORD: peertube
      POSTGRES_DB: peertube_prod

  redis:
    image: redis:alpine
    restart: always

  app:
    image: avhost/docker-peertube:latest
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
      - redis
    environment:
      PEERTUBE_ADMIN_EMAIL: "test@test.de"
      PEERTUBE_DB_HOSTNAME: "db"
      PEERTUBE_DB_PASSWORD: "peertube"
      PEERTUBE_DB_SUFFIX: "_prod"
      PEERTUBE_DB_USERNAME: "peertube"
      PEERTUBE_HOSTNAME: "localhost"
      PEERTUBE_INSTANCE_NAME: "example"
      PEERTUBE_REDIS_HOSTNAME: "redis"
      PEERTUBE_REDIS_PORT: "6379"
      PEERTUBE_SIGNUP_ENABLED: "false"
      PEERTUBE_TRANSCODING_ENABLED: "true"
